package snippets

// This file is generated by internal/langserver/handlers/snippets/snippets_gen_test.go
var snippetMap = map[string]Snippet{
	"applications": {
		ResourceType: "applications",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "applications"`,
			},
			{
				Name: "body",
				Value: `body = {
    displayName = "My Application"
  }`,
			},
		},
	},
	"applications/{}/federatedidentitycredentials": {
		ResourceType: "applications/{}/federatedIdentityCredentials",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "applications/${${1:"The id of the applications resource"}}/federatedIdentityCredentials"`,
			},
			{
				Name: "body",
				Value: `body = {
    name        = "myFederatedIdentityCredentials"
    description = "My test federated identity credentials"
    audiences   = ["https://myapp.com"]
    issuer      = "https://sts.windows.net/00000000-0000-0000-0000-000000000000/"
    subject     = "00000000-0000-0000-0000-000000000000"
  }`,
			},
		},
	},
	"groups": {
		ResourceType: "groups",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "groups"`,
			},
			{
				Name: "body",
				Value: `body = {
    displayName     = "My Group"
    mailEnabled     = false
    mailNickname    = "mygroup"
    securityEnabled = true
  }`,
			},
		},
	},
	"groups/{}/members/$ref": {
		ResourceType: "groups/{}/members/$ref",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "groups/${${1:"The id of the groups resource"}}/members/$ref"`,
			},
			{
				Name: "body",
				Value: `body = {
    "@odata.id" = "https://graph.microsoft.com/v1.0/directoryObjects/${${2:"The id of the servicePrincipals resource"}}"
  }`,
			},
		},
	},
	"oauth2permissiongrants": {
		ResourceType: "oauth2PermissionGrants",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "oauth2PermissionGrants"`,
			},
			{
				Name: "body",
				Value: `body = {
    clientId    = ${1:"The id of the servicePrincipals resource"}
    consentType = "AllPrincipals"
    resourceId  = ${2:"MSGraphServicePrincipalId"}
    scope       = "User.Read"
  }`,
			},
		},
	},
	"serviceprincipals": {
		ResourceType: "servicePrincipals",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "servicePrincipals"`,
			},
			{
				Name: "body",
				Value: `body = {
    appId = ${1:"TODO"}
  }`,
			},
		},
	},
	"serviceprincipals/{}/approleassignments": {
		ResourceType: "servicePrincipals/{}/appRoleAssignments",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "servicePrincipals/${${1:"MSGraphServicePrincipalId"}}/appRoleAssignments"`,
			},
			{
				Name: "body",
				Value: `body = {
    appRoleId   = ${2:"userReadAllAppRoleId"}
    principalId = ${3:"TestApplicationServicePrincipalId"}
    resourceId  = ${4:"MSGraphServicePrincipalId"}
  }`,
			},
		},
	},
	"users": {
		ResourceType: "users",
		Fields: []Field{
			{
				Name:  "url",
				Value: `url = "users"`,
			},
			{
				Name: "body",
				Value: `body = {
    accountEnabled    = false
    displayName       = "My User"
    mailNickname      = "myuser"
    userPrincipalName = "myuser@${${1:"domain"}}"
    passwordProfile = {
      forceChangePasswordNextSignIn = true
      password                      = "Str0ngP@ssword"
    }
  }`,
			},
		},
	},
}
